version: "3"

services:
  app:
    container_name: Grobber
    build: .
    image: myanimestream/grobber
    restart: always
    ports:
      - 80:80
    networks:
      - backend
    environment:
      - ARIAS_URL=http://arias:7200
      - MONGO_URI=mongodb://database:27017
      - CHROME_WS=ws://browserless:3000
      - PROXY_URL=http://proxy:8081
      - SENTRY_DSN
    depends_on:
      - arias
      - browserless
      - database
      - proxy

  arias:
    container_name: Arias
    image: myanimestream/arias
    restart: always
    environment:
      - AWS_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - STORAGETYPE
      - DEFAULTBUCKET
    expose:
      - 7200
    volumes:
      - downloads:/downloads
    networks:
      - backend

  database:
    container_name: MongoDB
    image: mongo
    restart: always
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - database:/data/db
    networks:
      - backend

  proxy:
    container_name: Scylla
    image: myanimestream/scylla
    restart: always
    ports:
      - 8899:8899
      - 8081:8081
    expose:
      - 8081
    volumes:
      - scylla:/var/www/scylla
    networks:
      - backend

  browserless:
    container_name: Browserless
    image: browserless/chrome
    restart: always
    environment:
      - MAX_CONCURRENT_SESSIONS=5
      - MAX_QUEUE_LENGTH=10
      - PREBOOT_CHROME=true
      - CONNECTION_TIMEOUT=300000
    expose:
      - 3000
    networks:
      - backend

volumes:
  database: {}
  downloads: {}
  scylla: {}

networks:
  backend: {}